defmodule Saleflow.Repo.Migrations.AddPhoneCalls do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:phone_calls, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :lead_id, :uuid
      add :user_id, :uuid
      add :caller, :text, null: false
      add :callee, :text, null: false
      add :duration, :bigint, null: false, default: 0
      add :call_log_id, :uuid
      add :received_at, :utc_datetime_usec, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create index(:phone_calls, [:callee])
    create index(:phone_calls, [:user_id])
    create index(:phone_calls, [:received_at])
  end

  def down do
    drop table(:phone_calls)
  end
end
