defmodule Saleflow.Repo.Migrations.AddRemindedAtFields do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:meetings) do
      add :reminded_at, :utc_datetime_usec
    end

    alter table(:leads) do
      add :callback_reminded_at, :utc_datetime_usec
    end
  end

  def down do
    alter table(:leads) do
      remove :callback_reminded_at
    end

    alter table(:meetings) do
      remove :reminded_at
    end
  end
end
