defmodule Saleflow.Repo.Migrations.AddLoginSessions do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:login_sessions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :user_id, :uuid, null: false
      add :session_token, :text, null: false
      add :ip_address, :text
      add :user_agent, :text
      add :device_type, :text
      add :browser, :text
      add :city, :text
      add :country, :text
      add :logged_in_at, :utc_datetime_usec, null: false
      add :last_active_at, :utc_datetime_usec, null: false
      add :logged_out_at, :utc_datetime_usec
      add :force_logged_out, :boolean, null: false, default: false
    end

    create unique_index(:login_sessions, [:session_token],
             name: "login_sessions_unique_session_token_index"
           )
  end

  def down do
    drop_if_exists unique_index(:login_sessions, [:session_token],
                     name: "login_sessions_unique_session_token_index"
                   )

    drop table(:login_sessions)
  end
end
