defmodule Saleflow.Repo.Migrations.AddAttendeeFieldsToMeetings do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:meetings) do
      add :attendee_email, :text
      add :attendee_name, :text
    end
  end

  def down do
    alter table(:meetings) do
      remove :attendee_name
      remove :attendee_email
    end
  end
end
