defmodule Saleflow.Repo.Migrations.AddSalesResources do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:quarantines, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :lead_id, :uuid, null: false
      add :user_id, :uuid, null: false
      add :reason, :text, null: false
      add :quarantined_at, :utc_datetime_usec, null: false
      add :released_at, :utc_datetime_usec, null: false
    end

    create table(:meetings, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :lead_id, :uuid, null: false
      add :user_id, :uuid, null: false
      add :title, :text, null: false
      add :meeting_date, :date, null: false
      add :meeting_time, :time, null: false
      add :notes, :text
      add :google_calendar_id, :text
      add :status, :text, null: false, default: "scheduled"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:call_logs, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :lead_id, :uuid, null: false
      add :user_id, :uuid, null: false
      add :outcome, :text, null: false
      add :notes, :text
      add :called_at, :utc_datetime_usec, null: false
    end

    create table(:assignments, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :lead_id, :uuid, null: false
      add :user_id, :uuid, null: false
      add :assigned_at, :utc_datetime_usec, null: false
      add :released_at, :utc_datetime_usec
      add :release_reason, :text
    end
  end

  def down do
    drop table(:assignments)

    drop table(:call_logs)

    drop table(:meetings)

    drop table(:quarantines)
  end
end
