defmodule Saleflow.Repo.Migrations.AddUserExtensionNumber do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add :extension_number, :text
    end

    create unique_index(:users, [:extension_number], name: "users_unique_extension_number_index")
  end

  def down do
    drop_if_exists unique_index(:users, [:extension_number],
                     name: "users_unique_extension_number_index"
                   )

    alter table(:users) do
      remove :extension_number
    end
  end
end
