defmodule Saleflow.Repo.Migrations.AddUserPhoneNumber do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add :phone_number, :text
    end

    create unique_index(:users, [:phone_number], name: "users_unique_phone_number_index")
  end

  def down do
    drop_if_exists unique_index(:users, [:phone_number], name: "users_unique_phone_number_index")

    alter table(:users) do
      remove :phone_number
    end
  end
end
