defmodule Saleflow.Repo.Migrations.AddLeads do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:leads, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :företag, :text, null: false
      add :telefon, :text, null: false
      add :epost, :text
      add :hemsida, :text
      add :adress, :text
      add :postnummer, :text
      add :stad, :text
      add :bransch, :text
      add :orgnr, :text
      add :omsättning_tkr, :text
      add :vinst_tkr, :text
      add :anställda, :text
      add :vd_namn, :text
      add :bolagsform, :text
      add :status, :text, null: false, default: "new"
      add :quarantine_until, :utc_datetime_usec
      add :callback_at, :utc_datetime_usec
      add :imported_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end
  end

  def down do
    drop table(:leads)
  end
end
