defmodule Saleflow.Repo.Migrations.AddDurationMinutesToMeetings do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:microsoft_connections, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :user_id, :uuid, null: false
      add :microsoft_user_id, :text, null: false
      add :email, :text, null: false
      add :access_token, :text, null: false
      add :refresh_token, :text, null: false
      add :token_expires_at, :utc_datetime_usec, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:microsoft_connections, [:user_id],
             name: "microsoft_connections_unique_user_index"
           )

    alter table(:meetings) do
      add :duration_minutes, :bigint, null: false, default: 30
      add :teams_join_url, :text
      add :teams_event_id, :text
    end

    alter table(:leads) do
      add :telefon_2, :text
    end
  end

  def down do
    alter table(:leads) do
      remove :telefon_2
    end

    alter table(:meetings) do
      remove :teams_event_id
      remove :teams_join_url
      remove :duration_minutes
    end

    drop_if_exists unique_index(:microsoft_connections, [:user_id],
                     name: "microsoft_connections_unique_user_index"
                   )

    drop table(:microsoft_connections)
  end
end
